### PR TITLE
Get rid of _replace_keys function

### PR DESCRIPTION
**Pull request by vmagamedov**

### CODE REVIEW

**Comment by vmagamedov** [comment]
After doing some profiling I found that `numeric` paramstyle in SQLAlchemy introduces additional overhead during query compilation (inside SQLAlchemy) and overall performance becomes worse than current implementation with `named` paramstyle. So I tried another way by using `pyformat` paramstyle (second commit in PR).

First I tried worst scenario:
```python
query = (
    select([table.c.name])
    .where(table.c.id.in_(list(range(1, 1000))))
)
```
This single query with thousand params:
- Current: 22088 function calls (21083 primitive calls) in 0.426 seconds
- Numeric: 26087 function calls (25082 primitive calls) in 0.438 seconds
- PyFormat: 19090 function calls (18085 primitive calls) in 0.410 seconds

The same query but with just 10 params and 100 iterations:
- Current: 30701 function calls (29201 primitive calls) in 0.048 seconds
- Numeric: 34601 function calls (33101 primitive calls) in 0.052 seconds
- PyFormat: 27901 function calls (26401 primitive calls) in 0.045 seconds

What I still don't understand is why `MissingParameterError` was needed? Are there cases when SQLAlchemy compiles queries without corresponding params?

**Comment by vmagamedov** [comment]
There are a minor bug in tests) I can fix it.

**Comment by nhumrich** [comment]
`MissingParameterError` is needed for when someone writes a query, such as `sa.text('select * from :table_name', params={})` and fails to pass in the parameter for something in the query that is required. This isnt really used when you write only in sqlalchemy, but if you add in your own parameterized text, this can happen.

**Comment by vmagamedov** [comment]
I don't have any issues with current implementation, I just stumbled upon this code during performance issues investigation and I was thinking about why such code exists and I thought that it can be improved/refactored/simplified.

**Comment by vmagamedov** [comment]
Do you have any comments about actual changes in the source code or you are not expecting such contributions, which are not contains critical fixes or new features?

**Comment by nhumrich** [comment]
The change is fine, I was just curious. As far as the status of this PR, MissingParameterError still needs to be handled, and some tests are failing.

**Comment by vmagamedov** [comment]
Just tried to write test-case and reproduce MissingParameterError:
```python
>>> query = sa.text('SELECT * FROM users WHERE users.id=:user_id')
>>> q, p = connection.compile_query(query)
>>> print(q, p)
SELECT * FROM users WHERE users.id=$1 [None]
```
And seems like that even for missing params there is `None` in `compiled.params`. So maybe it is not possible to raise MissingParameterError.

**Comment by vmagamedov** [comment]
I noticed that `inline` argument is also not working.

**Comment by vmagamedov** [comment]
And if you will try to pass that `inline` argument, `_replace_keys` function will fail in most cases, when param value is not a string:
```python
>>> query = sa.select([file_table]).where(file_table.c.id.in_([1, 2, 3]))
>>> connection.compile_query(query, inline=True)
Traceback (most recent call last):
  File "/Users/vm/ws/asyncpgsa/tests/test_connection.py", line 87, in test_inline
    connection.compile_query(query, inline=True)
  File "/Users/vm/ws/asyncpgsa/asyncpgsa/connection.py", line 84, in compile_query
    new_query, new_params = _replace_keys(compiled.string, params, inline=inline)
  File "/Users/vm/ws/asyncpgsa/asyncpgsa/connection.py", line 31, in _replace_keys
    querystring = querystring.replace(':' + name, value, 1)
TypeError: replace() argument 2 must be str, not int
```

**Comment by vmagamedov** [comment]
After my latest commit I ran my benchmarks again and got interesting numbers:

Query with 10 params and 100 iterations:
- Current: 30701 function calls (29201 primitive calls) in 0.048 seconds
- Latest pyformat: 26101 function calls (24601 primitive calls) in 0.042 seconds

Single query with 1000 params:
- Current: 22088 function calls (21083 primitive calls) in **0.426** seconds
- Latest pyformat: 17093 function calls (16088 primitive calls) in **0.022** seconds

For large queries improvement is **20x** in CPU time!

**Comment by vmagamedov** [comment]
Benchmark: https://gist.github.com/vmagamedov/e86ea70211d2a7f2064083e1c629d393

**Comment by nhumrich** [comment]
> So maybe it is not possible to raise MissingParameterError

I mean.. its doesn't break any tests.. so thats probably my fault for not adding a test for this case. Since it passes tests, its good enough for me. Thanks for your effort on this.

**Comment by nhumrich** [comment]
This will be in 0.22.0

**Pull request merged**
