### PR TITLE
Asyncpg record objects

### PR DESCRIPTION
**Pull request by rlittlefield**
This removes the Record and RecordGenerators in favor of the asyncpg Records. This means dot notation must be replaces with dict notation when accessing values, making this a breaking change. 

It also fixes an issue where the `_dialect` property on the SAConnection was not getting set, causing issues when trying to use the query builder with table definitions containing JSON types. This is also potentially breaking, as it enables automatic type coercion into a JSON string, even if you have already passed the structure through `json.dumps`.

It also re-enables the use of compile_query for several of the SAConnection types, so that SA query-builder queries will get properly converted.

It also proxies the `cursor` method of the parent connection, allowing SA queries to be used with cursors directly.

### CODE REVIEW

**Comment by rlittlefield** [comment]
Merged the latest changes from master. Based on some suggestions by Nick, I also removed the unneeded intermediate functions on the connection object, as the query conversion is happening in `_execute` now, and the only other thing they did was wrap the results in a Record object.

**Comment by keunhong** [comment]
When do you plan on merging this? Seems like a good change :)

**Comment by nhumrich** [comment]
Probably next week some time. It breaks backwards compatibilty significantly. So trying to decide if its really worth it. Probably is worth it, and will work better in the long run for compatibility with asyncpg.

**Comment by rlittlefield** [comment]
It looks like the CI builds are failing for the python nightly due to a missing wheel for asyncpg. Are we looking good to get this merged?

**Pull request merged**
