### PR TITLE
Added semver info, fixes #105

### LINKED ISSUE #105: Does this package follow semantic versioning?
Does this package follow [semantic versioning](https://semver.org) ([PEP 440](https://www.python.org/dev/peps/pep-0440/#semantic-versioning))? 
Is it safe to use ~= requirement operator?
```
asyncpgsa~=0.26.1
```

### PR DESCRIPTION
**Pull request by alvassin**

### CODE REVIEW

**Comment by alvassin** [comment]
@nhumrich, what happened which CI checks? I tried to search this project on Travis CI to investigate the problem, but was not able to.

**Comment by nhumrich** [comment]
@alvassin I have no idea. I am also not able to check, not being at CanopyTax anymore. I will reach out an see whats possible.

**Comment by alvassin** [comment]
Thank you very much. I tried to add new empty commit to bump CI, but that didn't help. 😔

**Comment by nhumrich** [comment]
Finally got everything working. Thank you for being patient

**Pull request merged**
